<!--<img class="image_article" src="images/image_article.jpg" alt="logo notaire" />-->
    <p>L’article 768 du Code Civil accorde à l’héritier une option entre trois partis : soit accepter purement et simplement la succession, soit renoncer à la succession, soit accepter à concurrence de l’actif net.<br>La décision d’opter pour l’acceptation ou la renonciation dépendra de la consistance de l’actif et du passif successoral. Cependant dans certains cas, il n’est pas aisé de savoir avec exactitude si la succession sera bénéficiaire ou déficitaire car l’étendue des engagements du défunt n’est pas aisément déterminable. Dans cette hypothèse, l’acceptation à concurrence de l’actif net sera l’option pour l’héritier et permettra d’éviter la confusion de ses biens personnels avec ceux de la succession. Il ne s’agit pas d’une option conditionnelle. Il s’agit d’une véritable acceptation qui confirme le suc- cessible dans sa qualité d’héritier.</p>
    <h4>À qui cette option est-elle ouverte ?</h4>
    <p>L’article 768 du Code Civil ne permet de choisir cette procédure de l’acceptation à concurrence de l’actif net que si l’héritier a une vocation universelle ou à titre universel. <br>L’acceptation à concurrence de l’actif net étant un acte un acte d’administration et de conservation, le tuteur n’a besoin d’aucune autorisation pour déclarer au greffe du tribunal judiciaire ou devant notaire qu’il accepte à concurrence de l’actif net. Le majeur sous curatelle peut également accepter seul une succession à concurrence de l’actif net. Il en est de même pour l’administrateur légal unique ou l’un des administrateurs légaux conjoints. Cette option présente donc également un intérêt en présence d’un hériter mineur et permet de faire cette déclaration sans autorisation d’un juge. L’héritier qui a une vocation à titre particulier ne peut qu’accepter purement et simplement ou renoncer à sa part.</p>
    <h4>Sous quel délai cette option s’exerce-t-elle ? </h4>
    <p>L’héritier doit opter avant le délai de prescription de 10 ans car au-delà il serait réputé renonçant. L’héritier peut s’il le souhaite opter dès l’ouverture de la succession. La loi lui accorde cependant un délai de 4 mois pendant lequel il ne peut être contraint d’opter (Article 771 du Code Civil). Passé ce délai, l’héritier conserve son option jusqu’à l’expiration de la dixième année suivant le décès. S’il est mis en demeure d’opter, il sera contraint de le faire dans le délai prévu à l’article 772 du Code Civil soit dans un délai de deux mois sauf octroi d’un délai supplémentaire. À défaut d’avoir pris parti à l’expiration du délai de deux mois, l’héritier est réputé acceptant pur et simple et l’option d’acceptation à concurrence de l’actif net ne lui est plus ouverte. </p>
    <h4>Comment cette option s’exerce-t-elle ?</h4>
    <p>L’héritier qui accepte à concurrence de l’actif net devra accomplir deux formalités :<br>– La déclaration au Greffe du Tribunal Judicaire du lieu d’ouverture de la succession ou devant notaire selon l’article 788 du code Civil Aucune formalité sacramentelle n’est exigée pour cette déclaration, il suffit que l’héritier exprime clairement le parti qu’il prend. La déclaration doit comporter la mention de l’élection de domicile unique qui peut être le domicile d’un des acceptants ou celui de la personne chargée du règlement de la succession. Si l’héritier a fait sa déclaration devant notaire, ce dernier en adressera copie au Tribunal dans le mois.<br>L’établissement d’un inventaire est prévu à l’article 789 du Code Civil. Il doit être déposé au tribunal judiciaire soit en même temps que la déclaration soit dans les 2 mois. Un délai supplémentaire peut être accordé en cas de motifs sérieux ou légitimes. À défaut de respect de ce délai, l’héritier est réputé avoir accepté purement et simplement la succession.</p>
    <h4>Quelles formalités de publicité faut-il effectuer ?</h4>
    <p>Le greffe inscrit la déclaration d’acceptation à concurrence de l’actif net sur un registre tenu à cet effet. Un récépissé est remis au déclarant. Une double publicité est effectuée :<br>– Le greffier procède à la publication de l’acceptation à concurrence de l’actif net au BODACC.<br>– L’héritier dans le délai d’un mois à compter de la déclaration fait procéder à l’insertion d’un avis dans un journal d’annonces légales. L’inventaire est soumis à la même publicité que la déclaration à savoir publication au BODACC et dans un journal d’annonces légales.</p>
    <h4>Quand le créancier successoral doit-il déclarer sa créance et comment déclarer sa créance ?</h4>
    <p>La publication de la déclaration d’acceptation à concurrence de l’actif net de l’héritier au greffe fait courir le délai de déclaration des créances par les créanciers de la succession. Les créanciers doivent déclarer leur créance dans un délai de 15 mois à compter de cette publicité. À défaut la créance se trouve éteinte sauf si elle est assortie d’une sureté réelle. Tous les créanciers de la succession doivent déclarer leur créance mais seules les créances de somme d’argent sont à déclarer.<br>Les créanciers doivent notifier leur créance au domicile élu de la succession, par lettre recommandée ou par voie d’huissier.</p>
    <h4>Comment l’héritier règle-t-il les dettes ?</h4>
    <p>L’héritier règle le passif selon l’ordre énoncé par l’article 796 du code civil. Ainsi les créanciers inscrits sont réglés en priorité selon le rang de leur sûreté. Sont ensuite payés les créanciers chirographaires qui ont déclaré leur créance dans l’ordre des déclarations. Les créanciers inscrits qui n’ont pas été désintéressés sont assimilés à des créanciers chirographaires.<br>Que se passe-t-il en cas d’insuffisance de l’actif successoral ? Les créanciers successoraux dont la créance n’a pas été réglée pour défaut d’actif, disposent d’un recours contre les légataires qui ont été remplis de leur droit. Ce recours est réservé aux créanciers qui ont régulièrement déclaré leur créance dans le délai de 15 mois. Ce recours n’est encadré dans aucun délai. Les créanciers diligents agiront dans les meilleurs délais.</p><br>
    <p>Par Me Laurence LICHTENBERGER, notaire à Bordeaux.</p>